const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Flash,
		C3.Behaviors.Fade,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.Function,
		C3.Plugins.Arr,
		C3.Plugins.LocalStorage,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Sin,
		C3.Behaviors.Pin,
		C3.Behaviors.Timer,
		C3.Behaviors.solid,
		C3.Behaviors.EightDir,
		C3.Plugins.Button,
		C3.Plugins.TextBox,
		C3.Plugins.Text,
		C3.Plugins.HTMLElement,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.System.Acts.SetVar,
		C3.Behaviors.EightDir.Acts.SetMaxSpeed,
		C3.Behaviors.EightDir.Acts.SetAcceleration,
		C3.Behaviors.EightDir.Acts.SetDeceleration,
		C3.Plugins.Arr.Acts.Clear,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.JavaScriptInEvents.Game_event_Event10_Act19,
		C3.JavaScriptInEvents.Game_event_Event10_Act20,
		C3.Plugins.System.Cnds.IsMobile,
		C3.Plugins.Spritefont2.Acts.SetSize,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.scrollx,
		C3.Plugins.System.Exps.scrolly,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.JavaScriptInEvents.Game_event_Event20_Act1,
		C3.JavaScriptInEvents.Game_event_Event20_Act2,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Exps.max,
		C3.Plugins.Spritefont2.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.JavaScriptInEvents.Game_event_Event37_Act1,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.JavaScriptInEvents.Game_event_Event43_Act1,
		C3.JavaScriptInEvents.Game_event_Event44_Act1,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Arr.Cnds.ArrForEach,
		C3.Plugins.Arr.Cnds.CompareCurrent,
		C3.Plugins.Arr.Exps.CurX,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Behaviors.Timer.Acts.StopTimer,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.JavaScriptInEvents.Game_event_Event163_Act3,
		C3.Plugins.System.Acts.WaitForSignal,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Arr.Acts.Sort,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Acts.RestartLayout,
		C3.JavaScriptInEvents.Game_event_Event177_Act2,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Exps.projectname,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.System.Acts.SetLayerScale,
		C3.Plugins.System.Exps.layeropacity,
		C3.Plugins.System.Exps.layerscale,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Browser.Acts.Vibrate,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.JavaScriptInEvents.Game_event_Event206_Act12,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.JavaScriptInEvents.Game_event_Event207_Act12,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Touch.Exps.TouchID,
		C3.Plugins.Function.Cnds.OnFunction,
		C3.Plugins.Function.Acts.SetReturnValue,
		C3.Plugins.System.Exps.canvastolayerx,
		C3.Plugins.Touch.Exps.AbsoluteXForID,
		C3.Plugins.Function.Exps.Param,
		C3.Plugins.Touch.Exps.AbsoluteYForID,
		C3.Plugins.System.Exps.canvastolayery,
		C3.JavaScriptInEvents.Game_event_Event234_Act8,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Browser.Acts.GoToURL,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.LoadURL,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Audio.Acts.Preload,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.Spritefont2.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.Spritefont2.Acts.SetBoolInstanceVar,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Cnds.LayerNameExists,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Mouse.Cnds.IsButtonDown,
		C3.Plugins.Mouse.Acts.SetCursorSprite,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Cnds.IsProcessingGets,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.System.Exps.windowwidth,
		C3.Plugins.System.Exps.windowheight,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.System.Cnds.LayerCmpOpacity,
		C3.Plugins.System.Acts.Signal,
		C3.JavaScriptInEvents.Menu_event_Event2_Act1,
		C3.JavaScriptInEvents.Menu_event_Event2_Act2,
		C3.JavaScriptInEvents.Menu_event_Event2_Act20,
		C3.JavaScriptInEvents.Menu_event_Event3_Act2,
		C3.JavaScriptInEvents.Menu_event_Event3_Act3,
		C3.JavaScriptInEvents.Menu_event_Event4_Act1,
		C3.Plugins.Spritefont2.Cnds.CompareText,
		C3.JavaScriptInEvents.Menu_event_Event5_Act2,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Browser.Acts.Close,
		C3.Plugins.TextBox.Acts.SetVisible,
		C3.JavaScriptInEvents.Menu_event_Event17_Act1,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.TextBox.Acts.SetText,
		C3.JavaScriptInEvents.Menu_event_Event24_Act6,
		C3.JavaScriptInEvents.Menu_event_Event26_Act5,
		C3.JavaScriptInEvents.Menu_event_Event33_Act2,
		C3.JavaScriptInEvents.Game_over_event_Event2_Act1,
		C3.JavaScriptInEvents.Game_over_event_Event5_Act1,
		C3.JavaScriptInEvents.Game_over_event_Event7_Act1,
		C3.Plugins.Button.Acts.SetVisible,
		C3.JavaScriptInEvents.Game_over_event_Event10_Act1,
		C3.JavaScriptInEvents.Game_over_event_Event11_Act1,
		C3.JavaScriptInEvents.Game_over_event_Event15_Act1,
		C3.JavaScriptInEvents.Game_over_event_Event16_Act1,
		C3.JavaScriptInEvents.Game_over_event_Event17_Act2,
		C3.Plugins.TextBox.Cnds.OnTextChanged,
		C3.Plugins.System.Exps.len,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.System.Exps.left,
		C3.JavaScriptInEvents.Auth_event_Event1_Act1,
		C3.JavaScriptInEvents.Auth_event_Event1_Act2,
		C3.JavaScriptInEvents.Auth_event_Event1_Act3,
		C3.JavaScriptInEvents.Auth_event_Event1_Act4,
		C3.JavaScriptInEvents.Auth_event_Event2_Act1,
		C3.JavaScriptInEvents.Auth_event_Event3_Act1,
		C3.JavaScriptInEvents.Bounties_event_Event2_Act1,
		C3.JavaScriptInEvents.Bounties_event_Event2_Act2,
		C3.JavaScriptInEvents.Bounties_event_Event2_Act7,
		C3.JavaScriptInEvents.Bounties_event_Event2_Act9,
		C3.JavaScriptInEvents.Bounties_event_Event2_Act10,
		C3.JavaScriptInEvents.Bounties_event_Event2_Act11,
		C3.JavaScriptInEvents.Bounties_event_Event3_Act1,
		C3.JavaScriptInEvents.Bounties_event_Event6_Act1,
		C3.JavaScriptInEvents.Bounties_event_Event8_Act1,
		C3.JavaScriptInEvents.Bounties_event_Event9_Act1,
		C3.JavaScriptInEvents.Bounties_event_Event10_Act1,
		C3.JavaScriptInEvents.Bounties_event_Event11_Act1,
		C3.JavaScriptInEvents.Bounties_event_Event12_Act2,
		C3.JavaScriptInEvents.Bounties_event_Event13_Act1,
		C3.JavaScriptInEvents.Bounties_event_Event14_Act1,
		C3.JavaScriptInEvents.Bounties_event_Event15_Act1,
		C3.JavaScriptInEvents.Bounties_event_Event16_Act1,
		C3.JavaScriptInEvents.Bounties_event_Event17_Act1,
		C3.JavaScriptInEvents.Bounties_event_Event18_Act1,
		C3.JavaScriptInEvents.Bounties_event_Event19_Act1,
		C3.JavaScriptInEvents.Leaderboard_event_Event1_Act1,
		C3.JavaScriptInEvents.Leaderboard_event_Event1_Act4,
		C3.JavaScriptInEvents.Leaderboard_event_Event3_Act2,
		C3.JavaScriptInEvents.Leaderboard_event_Event4_Act1,
		C3.JavaScriptInEvents.Leaderboard_event_Event5_Act1,
		C3.Plugins.System.Exps.dt,
		C3.JavaScriptInEvents.Leaderboard_event_Event8_Act1,
		C3.JavaScriptInEvents.Beta_event_Event1_Act1,
		C3.Plugins.Text.Acts.SetVisible,
		C3.JavaScriptInEvents.Beta_event_Event6_Act1,
		C3.JavaScriptInEvents.Beta_event_Event6_Act2,
		C3.JavaScriptInEvents.Wallet_event_Event2_Act1,
		C3.JavaScriptInEvents.Wallet_event_Event2_Act2,
		C3.JavaScriptInEvents.Wallet_event_Event3_Act1,
		C3.JavaScriptInEvents.Wallet_event_Event4_Act4,
		C3.JavaScriptInEvents.Wallet_event_Event4_Act6,
		C3.JavaScriptInEvents.Wallet_event_Event4_Act8,
		C3.JavaScriptInEvents.Wallet_event_Event4_Act9,
		C3.JavaScriptInEvents.Wallet_event_Event4_Act10,
		C3.JavaScriptInEvents.Wallet_event_Event7_Act1,
		C3.JavaScriptInEvents.Wallet_event_Event9_Act1,
		C3.JavaScriptInEvents.Wallet_event_Event10_Act1,
		C3.JavaScriptInEvents.Wallet_event_Event11_Act1,
		C3.JavaScriptInEvents.Wallet_event_Event12_Act1,
		C3.JavaScriptInEvents.Wallet_event_Event13_Act2,
		C3.JavaScriptInEvents.Wallet_event_Event14_Act1,
		C3.JavaScriptInEvents.Wallet_event_Event15_Act1,
		C3.JavaScriptInEvents.Wallet_event_Event16_Act1,
		C3.JavaScriptInEvents.Wallet_event_Event17_Act1,
		C3.JavaScriptInEvents.Wallet_event_Event18_Act1,
		C3.JavaScriptInEvents.Wallet_event_Event19_Act1,
		C3.JavaScriptInEvents.Wallet_event_Event20_Act1,
		C3.JavaScriptInEvents.Wallet_event_Event21_Act2,
		C3.JavaScriptInEvents.Wallet_event_Event21_Act3,
		C3.Plugins.HTMLElement.Acts.SetPos,
		C3.Plugins.TextBox.Acts.SetPos,
		C3.JavaScriptInEvents.Wallet_event_Event25_Act5
	];
};
self.C3_JsPropNameTable = [
	{Cursor_Pressed: 0},
	{Cursor: 0},
	{Dog_Dream: 0},
	{ID: 0},
	{Flash: 0},
	{Gui_Duck: 0},
	{Aim: 0},
	{Gui_Ducks: 0},
	{Gui_Ducks_Line: 0},
	{Gui_Score: 0},
	{Gui_Shot: 0},
	{Gui_Bullet: 0},
	{Gui_Hits: 0},
	{Fade: 0},
	{Frame_Instructions: 0},
	{XP: 0},
	{YP: 0},
	{ConAngle: 0},
	{Joystick: 0},
	{Joystick_Area: 0},
	{Gui_Reward: 0},
	{Ground: 0},
	{Background: 0},
	{Bush: 0},
	{Tree: 0},
	{Audio: 0},
	{Browser: 0},
	{Keyboard: 0},
	{Mouse: 0},
	{Touch: 0},
	{Function: 0},
	{Hit_Ducks: 0},
	{Kill_Ducks: 0},
	{LocalStorage: 0},
	{Round_Font: 0},
	{Top_Score_Font: 0},
	{Score_Font: 0},
	{Active: 0},
	{Loading_Font: 0},
	{Game_Score_Font: 0},
	{Orientation_Font: 0},
	{Round_Number_Font: 0},
	{Text_Principal: 0},
	{Text_Balance: 0},
	{LeaderboardText: 0},
	{Text_NewHighScoreMessage: 0},
	{Sine: 0},
	{Text_PaymentPrompt: 0},
	{Pin: 0},
	{GoldPot_Text: 0},
	{SilverPot_Text: 0},
	{WinAmount_Text: 0},
	{HighScorePot_Text: 0},
	{CountdownText: 0},
	{LeaderboardScores: 0},
	{Text_ConfirmMessage: 0},
	{Text_ConfirmRecipient: 0},
	{Timer: 0},
	{Text_ConfirmPromo: 0},
	{PaymentErrorText: 0},
	{PromoStatusText: 0},
	{Game_Score_Font2: 0},
	{Text_NewHighScoreMessage2: 0},
	{Button_Exit: 0},
	{Button_Fullscreen: 0},
	{Button_Menu: 0},
	{Button_Music: 0},
	{Button_Pause: 0},
	{Button_Return: 0},
	{Button_Sound: 0},
	{Button_Start: 0},
	{Button_Restart: 0},
	{Button_Attack: 0},
	{Game_Icon: 0},
	{Game_Logo: 0},
	{Black_Screen: 0},
	{White_Screen: 0},
	{Game_Logo2: 0},
	{Game_Logo3: 0},
	{Text_Paused: 0},
	{Text_Game_Over: 0},
	{Text_Fly_Away: 0},
	{Text_You_Score: 0},
	{Text_Perfect: 0},
	{Text_Round_Completed: 0},
	{Text_Round: 0},
	{Name: 0},
	{Solid: 0},
	{Collision_Level: 0},
	{Color: 0},
	{Collisions: 0},
	{Shot: 0},
	{Fall: 0},
	{Fly_Away: 0},
	{Target_Angle: 0},
	{FlyAwayDisplayed: 0},
	{Collision_Duck: 0},
	{Point: 0},
	{Collision_Point: 0},
	{Collision_Dog: 0},
	{"8Direction": 0},
	{Collision_Aim: 0},
	{Collision_GoldenDuck: 0},
	{Collision_SilverDuck: 0},
	{Move: 0},
	{Jump: 0},
	{Dog_Scene: 0},
	{isGolden: 0},
	{Ducks: 0},
	{Up: 0},
	{Down: 0},
	{Dog: 0},
	{Dog_Menu: 0},
	{Dog_Soul: 0},
	{ShotHandled: 0},
	{Ducks_Gold: 0},
	{Ducks_Silver: 0},
	{Button_Auth_InternetIdentity: 0},
	{Button_Auth_Plug: 0},
	{Button_CheckBalance: 0},
	{Button_Transfer: 0},
	{TextInput_Recipient: 0},
	{TextInput_Amount: 0},
	{Button_BackToMenu: 0},
	{Button_Manager: 0},
	{NameInputBox: 0},
	{EmailInputBox: 0},
	{Button_SubmitScore: 0},
	{Button_goto_leaderboard: 0},
	{FullPage_AdImage: 0},
	{Countdown: 0},
	{IsActive: 0},
	{Button_AdClose: 0},
	{TextInput_Password: 0},
	{Button_VerifyPassword: 0},
	{Text_StatusBeta: 0},
	{Button_ICPT_Deposit: 0},
	{Button_ICPT_Withdraw: 0},
	{Button_ICPT_CheckMyBalance: 0},
	{Button_ICPT_CheckOtherBalance: 0},
	{TextInput_OtherPrincipal: 0},
	{Text_Status: 0},
	{Sprite_HighScoreNotification: 0},
	{Sprite_DarkBG: 0},
	{Button_PayNow: 0},
	{Button_NoThanks: 0},
	{Button_AddSilverPot: 0},
	{Button_AddGoldPot: 0},
	{Button_GetSilverPot: 0},
	{Button_GetGoldPot: 0},
	{Button_GetTotalPot: 0},
	{TextInput_PotAmount: 0},
	{Button_ResetGold: 0},
	{Sprite_Leaderboard: 0},
	{Sprite_Play_Game: 0},
	{Sprite_Wallet: 0},
	{Sprite_PayNow: 0},
	{Sprite_NoThanks: 0},
	{Sprite_Wanted: 0},
	{Sprite_Wanted_Gold_Pot: 0},
	{Sprite_Logout: 0},
	{Sprite_Wanted_Silver_Pot: 0},
	{Shown: 0},
	{Sprite_SilverWin: 0},
	{Sprite_GoldWin: 0},
	{Sprite_Continue: 0},
	{Text_RoundsGold: 0},
	{Text_RoundsSilver: 0},
	{Text_LastGold: 0},
	{Text_LastSilver: 0},
	{Text_WinLog: 0},
	{Sprite: 0},
	{Sprite_latest_bounties: 0},
	{Sprite_Bounties: 0},
	{Sprite_Hunting_plaque_background: 0},
	{Sprite_Price: 0},
	{GoldOddsText: 0},
	{SilverOddsText: 0},
	{Sprite_MenuBG: 0},
	{Sprite_HighScoreInfo: 0},
	{Text: 0},
	{Sprite3: 0},
	{Text_TransactionLogs: 0},
	{Button_RefreshLogs: 0},
	{TansactionLogs: 0},
	{Sprite_BalanceBG: 0},
	{Sprite_YourICPTxt: 0},
	{Sprite_Transfer: 0},
	{Sprite_History: 0},
	{Sprite_CloseHistory: 0},
	{AverageRoundsText: 0},
	{OddsExplainText: 0},
	{Button_Score_Test: 0},
	{LastWinnerText: 0},
	{LastWinnerScoreText: 0},
	{LastWinnerAmountText: 0},
	{LastWinnerTimestampText: 0},
	{Sprite2: 0},
	{Sprite_ConfirmBG: 0},
	{Button_Confirm: 0},
	{Button_Cancel: 0},
	{Sprite_ConfirmDarkBG: 0},
	{PromoCodeInput: 0},
	{Button_SubmitPromo: 0},
	{Button_UsePromo: 0},
	{Sprite_SubmitScore: 0},
	{Buttons: 0},
	{Texts: 0},
	{Spawn_Duck: 0},
	{Game_Type: 0},
	{Aim_Speed: 0},
	{Downed_Ducks: 0},
	{Total_Ducks: 0},
	{Killed_Ducks: 0},
	{Duck_Color_1: 0},
	{Duck_Color_2: 0},
	{Duck_ID: 0},
	{Duck_X: 0},
	{Game_Speed: 0},
	{Game_Status: 0},
	{Shots: 0},
	{Level: 0},
	{Score: 0},
	{Top_Score: 0},
	{Count_Score: 0},
	{Lives: 0},
	{AdTypeInput: 0},
	{projectId: 0},
	{CurrentAdBase64: 0},
	{CurrentAdClickUrl: 0},
	{AdDisplayed: 0},
	{SpawnGoldenDuck: 0},
	{SpawnSilverDuck: 0},
	{GoldPot: 0},
	{SilverPot: 0},
	{JoystickFingerID: 0},
	{JoystickLocked: 0},
	{WinnerAmount: 0},
	{GoldWon: 0},
	{SilverWon: 0},
	{PotFetchBusy: 0},
	{GoldenCheckDone: 0},
	{SilverCheckDone: 0},
	{RoundCounted: 0},
	{ActiveDucks: 0},
	{GoldWinDisplayed: 0},
	{SilverWinDisplayed: 0},
	{SubRoundState: 0},
	{TouchID: 0},
	{Dist: 0},
	{Cangle: 0},
	{Radius: 0},
	{Dead_Zone: 0},
	{type: 0},
	{amount: 0},
	{Fullscreen: 0},
	{Sound: 0},
	{Sound_Status: 0},
	{Sound_Volume: 0},
	{Music: 0},
	{Music_Status: 0},
	{Music_Volume: 0},
	{Audio_Line_Width: 0},
	{isPaymentInProgress: 0},
	{message: 0},
	{GotHighScore: 0},
	{PlayerNameInput: 0},
	{HighScoreCheckComplete: 0},
	{Authenticated: 0},
	{currentPrincipal: 0},
	{TokenBalance: 0},
	{TokenRecipient: 0},
	{TokenAmount: 0},
	{SomeOtherPrincipal: 0},
	{PotAmount: 0},
	{RoundsSinceGoldWin: 0},
	{RoundsSinceSilverWin: 0},
	{LastGoldWinTs: 0},
	{LastSilverWinTs: 0},
	{RecentWinsJson: 0},
	{GoldDuckOdds: 0},
	{SilverDuckOdds: 0},
	{AverageRounds: 0},
	{LeaderboardString: 0},
	{HighScorePot: 0},
	{TimeLeftSeconds: 0},
	{LastWinnerName: 0},
	{LastWinnerScore: 0},
	{LastWinnerAmount: 0},
	{LastWinnerTimestamp: 0},
	{isBetaTester: 0},
	{UserInputPassword: 0},
	{StatusMessage: 0},
	{TransactionLogsText: 0},
	{success: 0}
];

self.InstanceType = {
	Cursor_Pressed: class extends self.ISpriteInstance {},
	Cursor: class extends self.ISpriteInstance {},
	Dog_Dream: class extends self.ISpriteInstance {},
	Gui_Duck: class extends self.ISpriteInstance {},
	Aim: class extends self.ISpriteInstance {},
	Gui_Ducks: class extends self.ISpriteInstance {},
	Gui_Ducks_Line: class extends self.ISpriteInstance {},
	Gui_Score: class extends self.ISpriteInstance {},
	Gui_Shot: class extends self.ISpriteInstance {},
	Gui_Bullet: class extends self.ISpriteInstance {},
	Gui_Hits: class extends self.ISpriteInstance {},
	Frame_Instructions: class extends self.ISpriteInstance {},
	Joystick: class extends self.ISpriteInstance {},
	Joystick_Area: class extends self.ISpriteInstance {},
	Gui_Reward: class extends self.ISpriteInstance {},
	Ground: class extends self.ISpriteInstance {},
	Background: class extends self.ISpriteInstance {},
	Bush: class extends self.ISpriteInstance {},
	Tree: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Function: class extends self.IInstance {},
	Hit_Ducks: class extends self.IArrayInstance {},
	Kill_Ducks: class extends self.IArrayInstance {},
	LocalStorage: class extends self.IInstance {},
	Round_Font: class extends self.ISpriteFontInstance {},
	Top_Score_Font: class extends self.ISpriteFontInstance {},
	Score_Font: class extends self.ISpriteFontInstance {},
	Loading_Font: class extends self.ISpriteFontInstance {},
	Game_Score_Font: class extends self.ISpriteFontInstance {},
	Orientation_Font: class extends self.ISpriteFontInstance {},
	Round_Number_Font: class extends self.ISpriteFontInstance {},
	Text_Principal: class extends self.ISpriteFontInstance {},
	Text_Balance: class extends self.ISpriteFontInstance {},
	LeaderboardText: class extends self.ISpriteFontInstance {},
	Text_NewHighScoreMessage: class extends self.ISpriteFontInstance {},
	Text_PaymentPrompt: class extends self.ISpriteFontInstance {},
	GoldPot_Text: class extends self.ISpriteFontInstance {},
	SilverPot_Text: class extends self.ISpriteFontInstance {},
	WinAmount_Text: class extends self.ISpriteFontInstance {},
	HighScorePot_Text: class extends self.ISpriteFontInstance {},
	CountdownText: class extends self.ISpriteFontInstance {},
	LeaderboardScores: class extends self.ISpriteFontInstance {},
	Text_ConfirmMessage: class extends self.ISpriteFontInstance {},
	Text_ConfirmRecipient: class extends self.ISpriteFontInstance {},
	Text_ConfirmPromo: class extends self.ISpriteFontInstance {},
	PaymentErrorText: class extends self.ISpriteFontInstance {},
	PromoStatusText: class extends self.ISpriteFontInstance {},
	Game_Score_Font2: class extends self.ISpriteFontInstance {},
	Text_NewHighScoreMessage2: class extends self.ISpriteFontInstance {},
	Button_Exit: class extends self.ISpriteInstance {},
	Button_Fullscreen: class extends self.ISpriteInstance {},
	Button_Menu: class extends self.ISpriteInstance {},
	Button_Music: class extends self.ISpriteInstance {},
	Button_Pause: class extends self.ISpriteInstance {},
	Button_Return: class extends self.ISpriteInstance {},
	Button_Sound: class extends self.ISpriteInstance {},
	Button_Start: class extends self.ISpriteInstance {},
	Button_Restart: class extends self.ISpriteInstance {},
	Button_Attack: class extends self.ISpriteInstance {},
	Game_Icon: class extends self.ISpriteInstance {},
	Game_Logo: class extends self.ISpriteInstance {},
	Black_Screen: class extends self.ISpriteInstance {},
	White_Screen: class extends self.ISpriteInstance {},
	Game_Logo2: class extends self.ISpriteInstance {},
	Game_Logo3: class extends self.ISpriteInstance {},
	Text_Paused: class extends self.ISpriteInstance {},
	Text_Game_Over: class extends self.ISpriteInstance {},
	Text_Fly_Away: class extends self.ISpriteInstance {},
	Text_You_Score: class extends self.ISpriteInstance {},
	Text_Perfect: class extends self.ISpriteInstance {},
	Text_Round_Completed: class extends self.ISpriteInstance {},
	Text_Round: class extends self.ISpriteInstance {},
	Collision_Level: class extends self.ISpriteInstance {},
	Collision_Duck: class extends self.ISpriteInstance {},
	Collision_Point: class extends self.ISpriteInstance {},
	Collision_Dog: class extends self.ISpriteInstance {},
	Collision_Aim: class extends self.ISpriteInstance {},
	Collision_GoldenDuck: class extends self.ISpriteInstance {},
	Collision_SilverDuck: class extends self.ISpriteInstance {},
	Dog_Scene: class extends self.ISpriteInstance {},
	Ducks: class extends self.ISpriteInstance {},
	Dog: class extends self.ISpriteInstance {},
	Dog_Menu: class extends self.ISpriteInstance {},
	Dog_Soul: class extends self.ISpriteInstance {},
	Ducks_Gold: class extends self.ISpriteInstance {},
	Ducks_Silver: class extends self.ISpriteInstance {},
	Button_Auth_InternetIdentity: class extends self.ISpriteInstance {},
	Button_Auth_Plug: class extends self.ISpriteInstance {},
	Button_CheckBalance: class extends self.IButtonInstance {},
	Button_Transfer: class extends self.IButtonInstance {},
	TextInput_Recipient: class extends self.ITextInputInstance {},
	TextInput_Amount: class extends self.ITextInputInstance {},
	Button_BackToMenu: class extends self.IButtonInstance {},
	Button_Manager: class extends self.IButtonInstance {},
	NameInputBox: class extends self.ITextInputInstance {},
	EmailInputBox: class extends self.ITextInputInstance {},
	Button_SubmitScore: class extends self.IButtonInstance {},
	Button_goto_leaderboard: class extends self.IButtonInstance {},
	FullPage_AdImage: class extends self.ISpriteInstance {},
	Button_AdClose: class extends self.ISpriteInstance {},
	TextInput_Password: class extends self.ITextInputInstance {},
	Button_VerifyPassword: class extends self.IButtonInstance {},
	Text_StatusBeta: class extends self.ITextInstance {},
	Button_ICPT_Deposit: class extends self.IButtonInstance {},
	Button_ICPT_Withdraw: class extends self.IButtonInstance {},
	Button_ICPT_CheckMyBalance: class extends self.IButtonInstance {},
	Button_ICPT_CheckOtherBalance: class extends self.IButtonInstance {},
	TextInput_OtherPrincipal: class extends self.ITextInputInstance {},
	Text_Status: class extends self.ITextInstance {},
	Sprite_HighScoreNotification: class extends self.ISpriteInstance {},
	Sprite_DarkBG: class extends self.ISpriteInstance {},
	Button_PayNow: class extends self.IButtonInstance {},
	Button_NoThanks: class extends self.IButtonInstance {},
	Button_AddSilverPot: class extends self.IButtonInstance {},
	Button_AddGoldPot: class extends self.IButtonInstance {},
	Button_GetSilverPot: class extends self.IButtonInstance {},
	Button_GetGoldPot: class extends self.IButtonInstance {},
	Button_GetTotalPot: class extends self.IButtonInstance {},
	TextInput_PotAmount: class extends self.ITextInputInstance {},
	Button_ResetGold: class extends self.IButtonInstance {},
	Sprite_Leaderboard: class extends self.ISpriteInstance {},
	Sprite_Play_Game: class extends self.ISpriteInstance {},
	Sprite_Wallet: class extends self.ISpriteInstance {},
	Sprite_PayNow: class extends self.ISpriteInstance {},
	Sprite_NoThanks: class extends self.ISpriteInstance {},
	Sprite_Wanted: class extends self.ISpriteInstance {},
	Sprite_Wanted_Gold_Pot: class extends self.ISpriteInstance {},
	Sprite_Logout: class extends self.ISpriteInstance {},
	Sprite_Wanted_Silver_Pot: class extends self.ISpriteInstance {},
	Sprite_SilverWin: class extends self.ISpriteInstance {},
	Sprite_GoldWin: class extends self.ISpriteInstance {},
	Sprite_Continue: class extends self.ISpriteInstance {},
	Text_RoundsGold: class extends self.ITextInstance {},
	Text_RoundsSilver: class extends self.ITextInstance {},
	Text_LastGold: class extends self.ITextInstance {},
	Text_LastSilver: class extends self.ITextInstance {},
	Text_WinLog: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite_latest_bounties: class extends self.ISpriteInstance {},
	Sprite_Bounties: class extends self.ISpriteInstance {},
	Sprite_Hunting_plaque_background: class extends self.ISpriteInstance {},
	Sprite_Price: class extends self.ISpriteInstance {},
	GoldOddsText: class extends self.ITextInstance {},
	SilverOddsText: class extends self.ITextInstance {},
	Sprite_MenuBG: class extends self.ISpriteInstance {},
	Sprite_HighScoreInfo: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Text_TransactionLogs: class extends self.ITextInstance {},
	Button_RefreshLogs: class extends self.IButtonInstance {},
	TansactionLogs: class extends self.IHTMLElementInstance {},
	Sprite_BalanceBG: class extends self.ISpriteInstance {},
	Sprite_YourICPTxt: class extends self.ISpriteInstance {},
	Sprite_Transfer: class extends self.ISpriteInstance {},
	Sprite_History: class extends self.ISpriteInstance {},
	Sprite_CloseHistory: class extends self.ISpriteInstance {},
	AverageRoundsText: class extends self.ITextInstance {},
	OddsExplainText: class extends self.ITextInstance {},
	Button_Score_Test: class extends self.IButtonInstance {},
	LastWinnerText: class extends self.ITextInstance {},
	LastWinnerScoreText: class extends self.ITextInstance {},
	LastWinnerAmountText: class extends self.ITextInstance {},
	LastWinnerTimestampText: class extends self.ITextInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite_ConfirmBG: class extends self.ISpriteInstance {},
	Button_Confirm: class extends self.ISpriteInstance {},
	Button_Cancel: class extends self.ISpriteInstance {},
	Sprite_ConfirmDarkBG: class extends self.ISpriteInstance {},
	PromoCodeInput: class extends self.ITextInputInstance {},
	Button_SubmitPromo: class extends self.ISpriteInstance {},
	Button_UsePromo: class extends self.ISpriteInstance {},
	Sprite_SubmitScore: class extends self.ISpriteInstance {},
	Buttons: class extends self.ISpriteInstance {},
	Texts: class extends self.ISpriteInstance {}
}